### App Settings #############################################
# Update every [10] minutes
update_rate: 10
metar_file: /tmp/metar
taf_file: /tmp/taf
###############################################################

### LED Settings #############################################
# LED Brightness

# LED Colors for various conditions.
# All colors are an array of R, G, B values.
led:
  brightness: 10
  colors:
    vfr: '#04a60e'
    mvfr: '#032ef1'
    ifr: '#c40000'
    lifr: '#e12ae2'
###############################################################




### Hardware Settings #########################################
# A list (array) of airports to be displayed on the map
#
# The order of this list must match the way the LEDs are
# wired otherwise you will get incorrect results
airports:
  - KSMQ
  - KFWN
  - KMMU
  - KLDJ
  - KCDW
  - KEWR
  - KJFK
  - KFRG
  - KISP
  - KHWV
  - KFOK
  - KHTO
  - KBDR
  - KLGA
  - KTEB
  - KHPN
  - KDXR
  - KHVN
  - KSNC
  - KGON
  - KWST
###############################################################
