### App Settings #############################################
# Update every [10] minutes
update_rate: 10
metar_file: /tmp/metar
taf_file: /tmp/taf
log_file: /var/log/metar_map.log
error_log_file: /var/log/metar_map.error.log

# Which library to use to control our neopixels
#   [node-pixel] | ws281x-native
driver: 'node-pixel'
###############################################################



### LED Settings #############################################
# LED Colors for various conditions.
# All colors are a string of HTML style hex colors (eg #ffffff)
led:
  brightness: 10
  colors:
    vfr: '#04a60e'
    marginal: '#032ef1'
    ifr: '#c40001'
###############################################################



### Hardware Settings #########################################
# A list (array) of airports to be displayed on the map
#
# The order of this list must match the way the LEDs are
# wired otherwise you will get incorrect results
#
# airports:
#   - KFWN
#   - KSMQ
###############################################################
